#!/bin/bash
IPADDRESS=$( /sbin/ifconfig eth0 | grep -oP "inet addr:\d+\.\d+\.\d+\.\d+" |     grep -oP "\d+\.\d+\.\d+\.\d+")
sed -i "s;local#http://\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\};local#http://$IPADDRESS;" /etc/swift/proxy-server.conf

swift-init main start
